// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmvoippjkkaxbohltogp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtdm9pcHBqa2theGJvaGx0b2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzE0MjMsImV4cCI6MjA2MTM0NzQyM30.4KyxLslkaQSNpvE7AeBVMvEqy4mUG544Pclh_9-IIZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});